apiVersion: v1
kind: Pod 

metadata:
  name: "goserver"
  labels:
    app: "goserver"
    name: goserver
spec:
  containers:
  - name: goserver
    image: "kennymack/hello-go:latest"
#    resources:
#      limits:
#        memory: "128Mi"
#        cpu: "500m"
#    ports:
#      - containerPort: <Port>
